config/routes.rb
Kegerator::Application.routes.draw do
  resources :users
  get 'set_user' => "users#set_user"
  post 'rate' => "users#rate"
  get 'ordered' => "users#ordered"

  root "users#index"

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	has_many :reviews
	validates :name, presence: true

	scope :ordered, -> { where(ordered: true) } 

	def self.unordered
		Beer.all.map { |b| b if !b.ordered}.compact
	end

	def average_rating
		i = 0
		reviews.map { |r| i += r.rating }
		i = i/reviews.count unless i == 0
		i == 0 ? "-" : i
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :beer
	validates :user_id, :beer_id, :rating, presence: true

	RATING = (1..5).to_a.push("-")
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	has_many :beers, through: :reviews
	validates :name, presence: true

	def average_review
		i = 0
		reviews.map{ |r| i += r.rating }
		i = i/(reviews.count) unless i == 0
		i
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# if Rails.env.production?
    # http_basic_authenticate_with :name => ENV['NAME'], :password => ENV['PING'], :except => [:show]
    # http_basic_authenticate_with :name => "test", :password => "test"
  # end
	before_filter :user, only: [:update, :edit]
	def index
		@user = User.find_by_id(session[:user], include: :reviews)
		@users = User.all.order(:name)
		@reviews = @user.reviews if @user
		@rated_beers = @reviews.map(&:beer).uniq if @reviews
		@ordered = Beer.ordered
		@beers = Beer.all.order("name asc")
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		else
			render action: :new
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to root_path
		else
			render action: :edit
		end
	end

	def set_user
		session[:user] = params[:user_id]
		redirect_to root_path
	end

	def rate
		Review.create(user_id: session[:user], rating: params[:rating], beer_id: params[:beer_id])
		redirect_to root_path
	end

	def ordered
		beer_id = params[:beer_id]
		beer = Beer.find(beer_id)
		beer.ordered = true
		beer.save
		redirect_to root_path
	end

	private

	def user
    @user = User.find(params[:id])
  end

	def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def latest_review(user)
		unless user && user.reviews.empty?
			"#{user.reviews.last.beer.name} - #{user.reviews.last.rating}"	
		else
			"No reviews yet"
		end
	end
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
  %title Touterator
  %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
  %link{rel: "icon", type: "image/png", href: "../assets/bsquare.png"}
  = stylesheet_link_tag    "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

  %body
    .container.clearfix
      = yield      

app/views/users/_form.html.haml
- @user.errors.full_messages.each do |msg|
  %p= msg

= f.label :name
%br
= f.text_field :name
%br
%br
= f.submit :submit, class: 'btn btn-default'

app/views/users/edit.html.haml
.title Edit - #{@user.name}
%br
= form_for @user, url: user_path(@user) do |f|
  = render partial: "form", locals: { f: f }

app/views/users/index.html.haml
- if @user
	%div.left
		%h3 Beer Options
		%table.table.table-hover
			%thead
				%tr
					%th Name
					%th Rating (1 - Nope, 5 - Yup)
					%th Avg Review
			%tbody
			- @beers.each do |beer|
				%tr{id: "beer_#{beer.id}"}
					%td= beer.name
					%td.ratings
						- if @user.beers.include?(beer)
							= @reviews.find_by_beer_id(beer.id).rating
						- else
							= select_tag "ratings", options_for_select(Review::RATING, "-"), {data: {beer_id: beer.id}}
					%td= beer.average_rating
					- if (@user.id == 1 || @user.id == 2)
						%td.ordered{data: {beer_id: beer.id }} Select

	%div.right
		%h3 What Others Rated
		%table.table.table-hover
			%thead
				%tr
					%th Name
					%th Latest Review
					%th Avg Review
			%tbody
			- @users.each do |user|
				%tr{id: "user_#{user.id}"}
					%td= user.name
					%td= latest_review(user)
					%td= user.average_review
		- unless @ordered.empty?
			%h3 Ordered Beers
			%table.table.table-hover
				%thead
					%tr
						%th Name
						%th Average Rating
				%tbody
				- @ordered.each do |beer|
					%tr{id: "beer_#{beer.id}"}
						%td= beer.name
						%td= beer.average_rating
- else
	%div#select-name
		%h3 Who are you?
		= select_tag "users", options_from_collection_for_select(@users, "id", "name"), prompt: "Select Name"

:javascript
	$("#users").change(function() {
		userId = $("#users").val();

		$.ajax({
			type: "GET",
			url: "/set_user",
			data: {user_id: userId}
		}).success(function(){
			location.reload();
		});
	});

	$(".ratings").change(function(e) {
		rating = $(e.target).val();
		beerId = $(e.target).data("beerId");
		$.ajax({
			type: "POST",
			url: "/rate",
			data: {rating: rating, beer_id: beerId}
		}).success(function(){
			location.reload();
		});
	});

	$(".ordered").click(function(e) {
		beerId = $(e.target).data("beerId");
		$.ajax({
			type: "GET",
			url: "/ordered",
			data: {beer_id: beerId}
		}).success(function(){
			console.log("LOC", location)
			location.reload();
		});
	})

app/views/users/new.html.haml
.title New User
%br
= form_for @user, url: users_path do |f|
  = render partial: "form", locals: { f: f }